# These are supported funding model platforms

github: [acetechnology]
custom: ['https://paystack.com/pay/acetech-plug-and-play','https://www.paypal.com/donate/?hosted_button_id=5QULG9MZSLL5J']
# liberapay: AceTechnology
